#!/bin/sh
#############################################################################
##
#W  make_doc          make Example Package documentation          Greg Gamble
##
#H  $Id: make_doc,v 4.1 2001/10/07 02:37:40 gap Exp $
##
##  This shell script uses TeX, BibTeX and MakeIndex to build the .dvi, Adobe
##  PDF, PostScript (commented out) and  HTML  (provided  you  have  tth  and
##  etc/convert.pl) documentation for the Example Package.
##

echo "TeXing documentation"
tex manual
bibtex manual
tex manual; ../../../doc/manualindex manual
tex manual
dvips -D300 manual -o
pdftex manual; pdftex manual

mkdir -p ../htm echo "Creating HTML documentation"
./convert.pl -t -c -n Nilmat . ../htm

#############################################################################
##
#E
