clean:
	echo "make xsemi to rebuild the files for xsemigroup"
	echo "make xaut to rebuild the files for xautomaton"


xsemi:
	rm -f xsemi_new_funcs.tcl.*
	touch xsemi_new_funcs.tcl.menu1
	touch xsemi_new_funcs.tcl.menu2
	touch xsemi_new_funcs.tcl.menu3
	touch xsemi_new_funcs.tcl.menu4
	touch xsemi_new_funcs.tcl.procs
	touch xsemi_new_funcs.tcl.names
	chmod a+w xsemi_new_funcs.tcl.menu1 xsemi_new_funcs.tcl.menu2 xsemi_new_funcs.tcl.menu3 xsemi_new_funcs.tcl.menu4 xsemi_new_funcs.tcl.procs xsemi_new_funcs.tcl.names

xaut:
	rm -f xaut_new_funcs.tcl.*
	touch xaut_new_funcs.tcl.menu
	touch xaut_new_funcs.tcl.procs
	touch xaut_new_funcs.tcl.names
	chmod a+w xaut_new_funcs.tcl.menu xaut_new_funcs.tcl.procs xaut_new_funcs.tcl.names
